spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:demo}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:demo}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    cache:
      type: redis

server:
  port: ${SERVER_PORT:8080}

env:
  security:
    jwt-secret: ${JWT_SECRET:thisIsASecretKey}
    jwt-expiration: ${JWT_EXPIRATION:3600000}
    refresh-expiration: ${REFRESH_EXPIRATION:172800000}
